# Site settings
title: Augmented Humans Conference 2025
url: https://augmented-humans.org
description: "The Augmented Humans (AHs) International Conference will be held in Melbourne, Australia focusing on physical, cognitive, and perceptual augmenting humans through digital technologies."
keywords: "Augmented Human, HCI, Human Computer Integration, Computer Science"
meta_author: Augmented Humans
baseurl: ""

mailchimp: "https://augmented-humans.us19.list-manage.com/subscribe/post?u=24833caa46a883a452cd0007c&amp;id=38ddd23071"

# Build settings
plugins: [jekyll-paginate, jekyll-feed, jekyll-sitemap, jekyll-seo-tag]

markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 10
paginate_path: "/blog/page:num/"
defaults:
  - scope:
      path: "img/posts/**"
      path: "sessions/**"
    values:
      sitemap: false

exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

imagesurl: "/img/closing/img/"
thumbsurl: "/img/closing/thumbs/"